
import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        {/* <Navbar /> */}
        <main className="p-6">
          <CartProvider>
      {children}
    </CartProvider>
        </main> 
      </body>
    </html>
  );
}
